pipeline {
  agent any

  stages {
    stage('Clone Code') {
      steps {
        git 'https://github.com/devrahul16/devops-ci-cd-k8s-project.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devrahul16/webapp:latest app'
      }
    }

    stage('Push Docker Image') {
      steps {
        sh 'docker push devrahul16/webapp:latest'
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s'
      }
    }
  }
}

