pipeline {
  agent any

  stages {

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devrahul16/webapp:latest app'
      }
    }

    stage('Push Docker Image') {
      steps {
        sh 'docker push devrahul16/webapp:latest'
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s'
      }
    }
  }
}
